server:
  port: ${SERVER_PORT:9001}

spring:
  application:
    name: test

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DBNAME:server}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DBNAME:server}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: public
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect